"""Add mobile, OAuth fields, and OTP table

Revision ID: 47529fc5cadf
Revises: 89e36e2bd292
Create Date: 2026-03-07 16:43:29.704814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47529fc5cadf'
down_revision: Union[str, None] = '89e36e2bd292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_type', sa.Enum('EMAIL', 'MOBILE', name='otptype'), nullable=False, comment='Type of OTP: email or mobile'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='6-digit OTP code'),
    sa.Column('recipient', sa.String(length=255), nullable=False, comment='Email address or mobile number'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='OTP expiration time (5 minutes)'),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True, comment='OAuth provider: google, microsoft, or null for manual signup'))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True, comment='OAuth provider user ID'))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('mobile_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'mobile_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'mobile')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
